/*
 * Homework #1
 * PrimeNumbers.java
 * Course: CS112 Java Programming
 * Instructor: Bhattacharyya
 * Name: Marc Goldstein
 * Student ID: 800-28-3313
 */

/*
A number is prime if it is divisible by 1 and the number itself and no other number. 
One is not a prime number because it does not have two distinct divisors.
*/
import javax.swing.JOptionPane; // import class JOptionPane

public class PrimeNumbers
{
  /* 
  This method tests whether a given number is prime or not. 
  Returns boolean value to method call in main method.
  Set to private, as only needs to be accessible from main method of this class.
  */
  private static boolean testPrime(int num)
  {
  	// begin assuming all numbers are prime until proven false 
    boolean isPrime = true;

	/* 
	Check if number equals one. 
	One is not a prime number because it does not have two distinct divisors.
	Set boolean to false, return boolean value to method call.
	*/
	if (num == 1)
	{
		isPrime = false;
		return isPrime;
	}

	/*
	If number is not equal to one, continue test.
	*/
	else 
	{
		/* 
    	Initialize int limit for subsequent loop.
		Limit upper range of divisors in the loop to the square root of the test number, as divisors larger than
		that are not useful.
		Cast square root as type int to drop fractional value.
		*/
		int limit = (int) Math.sqrt(num);  

		/* 
		Loop to evaluate if the test number is prime. 
		Loop through range of divisors for the number to test. Since a prime is only divisible by one and itself, 
		begin loop with number 2. Limit upper range to square root of target number, since divisors larger than
		that are not useful.
		*/
		for (int i = 2; i <= limit; i++) // increment from 2 to square root of target number
		{
			/* 
			Is number divible with remainder zero? If yes, then the number is not prime. 
			Set boolean to false, break out of loop.
			*/
			if (num % i == 0)
			{
				isPrime = false;
				break;
			} // end if number is divisible with remainder zero

		} // end for loop

		// Return boolean value to method call.	
		return isPrime;
		}

	} // end method testPrime

	// main method
	public static void main(String[] args)
	{
		// Initialize variables
		String listPrimes = ""; // string to store list of prime numbers
		int max = 100; // set upper limit of numbers to test here

		/* 
		Loop through all numbers from 1 to 100.
		Test each number by passing it to method testPrime.
		*/
		for (int i = 1; i <= max; i++)
		{
			/* 
			Call method testPrime in if statement, passing current number to evaluate in variable i parameter. 
			Method testPrime returns boolean true/false to if statement.
			If method testPrime returns true, append number to String listPrimes.
			*/
			if (testPrime(i)) 
			{
				listPrimes += i + " ";
			} // end if

		} // end for loop

	/*
	Write String listPrimes, which contains list of prime numbers generated by program, to JOptionPane dialog window.
	*/
	JOptionPane.showMessageDialog(null, "Prime numbers between 1 and 100:\n" + listPrimes,
	"PrimeNumbers.java", JOptionPane.INFORMATION_MESSAGE);

	} // end main method

} // end class PrimeNumbers